name: 'Build and Test'
on:
  push:
    branches-ignore: ['trunk']
  pull_request:
    branches: ['trunk']

env:
  BUILD_TYPE: Release

jobs:
  'build':
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    runs-on: ${{matrix.os}}
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          submodules: 'recursive'
      - name: 'Configure CMake'
        run: cmake -B '${{github.workspace}}/build' -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: 'Build'
        run: cmake --build '${{github.workspace}}/build' --config ${{env.BUILD_TYPE}}
      - name: 'Test'
        working-directory: '${{github.workspace}}/build'
        run: ctest -C ${{env.BUILD_TYPE}}
      - name: 'Upload test logs'
        uses: 'actions/upload-artifact@v3'
        with:
          name: 'Test logs'
          path: '${{github.workspace}}/build/Testing/Temporary/LastTest.log'

